export const stockData = [
    {
      namaBarang: "Casing iPhone 13",
      jumlahMasuk: 11,
      jumlahKeluar: 11,
      stokSisa: 0,
      totalPembelian: 275000,
      hargaRata: 25000,
      aset: 0,
      image: "/images/same-image.jpg",
    },
    {
      namaBarang: "Casing iPhone 12",
      jumlahMasuk: 15,
      jumlahKeluar: 14,
      stokSisa: 1,
      totalPembelian: 330000,
      hargaRata: 22000,
      aset: 22000,
      image: "/images/same-image.jpg",
    },
    {
      namaBarang: "Casing Samsung S22",
      jumlahMasuk: 12,
      jumlahKeluar: 11,
      stokSisa: 1,
      totalPembelian: 360000,
      hargaRata: 30000,
      aset: 30000,
      image: "/images/same-image.jpg",
    },
    {
      namaBarang: "Casing Oppo A54",
      jumlahMasuk: 17,
      jumlahKeluar: 13,
      stokSisa: 4,
      totalPembelian: 340000,
      hargaRata: 20000,
      aset: 80000,
      image: "/images/same-image.jpg",
    },
    {
      namaBarang: "Casing Xiaomi Redmi 10",
      jumlahMasuk: 14,
      jumlahKeluar: 12,
      stokSisa: 2,
      totalPembelian: 378000,
      hargaRata: 27000,
      aset: 54000,
      image: "/images/same-image.jpg",
    },
    {
      namaBarang: "Casing iPhone 11",
      jumlahMasuk: 15,
      jumlahKeluar: 14,
      stokSisa: 1,
      totalPembelian: 450000,
      hargaRata: 30000,
      aset: 30000,
      image: "/images/same-image.jpg",
    },
    {
      namaBarang: "Casing Vivo V21",
      jumlahMasuk: 15,
      jumlahKeluar: 13,
      stokSisa: 2,
      totalPembelian: 315000,
      hargaRata: 21000,
      aset: 42000,
      image: "/images/same-image.jpg",
    },
    {
      namaBarang: "Casing Realme 7",
      jumlahMasuk: 14,
      jumlahKeluar: 12,
      stokSisa: 2,
      totalPembelian: 350000,
      hargaRata: 25000,
      aset: 50000,
      image: "/images/same-image.jpg",
    },
    {
      namaBarang: "Casing Samsung A32",
      jumlahMasuk: 20,
      jumlahKeluar: 8,
      stokSisa: 12,
      totalPembelian: 560000,
      hargaRata: 28000,
      aset: 336000,
      image: "/images/same-image.jpg",
    },
    {
      namaBarang: "Casing Oppo F11",
      jumlahMasuk: 15,
      jumlahKeluar: 11,
      stokSisa: 4,
      totalPembelian: 345000,
      hargaRata: 23000,
      aset: 92000,
      image: "/images/same-image.jpg",
    },
  ];
  